apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- comentario/
- configmap-git-sync-env.yaml
- ingress-docs-aidbox.yaml
- ingress-fhirbase.yaml
- ingress.yaml
- meilisearch/
- monitoring/
- ns.yaml
- pdb.yaml
- remark42/
- service.yaml
- statefulset.yaml
- vpa.yaml
