apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: comentario
  namespace: gitbok
  labels:
    app.kubernetes.io/name: comentario
    app.kubernetes.io/component: comment-system
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    nginx.ingress.kubernetes.io/configuration-snippet: |
      sub_filter '<base href="docs/futureblog/comentario/' '<base href="/docs/futureblog/comentario/';
      sub_filter_once on;
      sub_filter_types text/html;
spec:
  ingressClassName: nginx
  rules:
  - host: www.health-samurai.io
    http:
      paths:
      - backend:
          service:
            name: comentario
            port:
              number: 80
        path: /docs/futureblog/comentario
        pathType: Prefix
