apiVersion: v1
kind: ServiceAccount
metadata:
  name: comentario-backup
  namespace: gitbok
  labels:
    app.kubernetes.io/name: comentario
    app.kubernetes.io/component: backup
  annotations:
    iam.gke.io/gcp-service-account: comentario-backup@samurai-backoffice.iam.gserviceaccount.com
